### ISSUE TITLE
Game Crash when clicking on any Mod

### ISSUE THREAD

**Issue by saltorio** [UniversalLP/JustEnoughButtons#52]
With Just Enough Buttons installed (both the version available yesterday, as well as today's updfate), my game will crash back to the desktop any time I go into the **_Mods_** menu and click on **any** mod that has **_Config_** options available (such as Waila).

I'm running MC 1.14.4 with Forge 1.14.4 - 28.1.0

[Here are my mods.](https://imgur.com/a/R8IAfY9)

Crash report:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/10/19 9:34 PM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at de.univrsal.justenoughbuttons.client.handlers.InventorySaveHandler.lambda$init$0(InventorySaveHandler.java:40) ~[?:1.14.4-1.0] {}
	at de.univrsal.justenoughbuttons.client.handlers.InventorySaveHandler$$Lambda$3576/1135127963.onPress(Unknown Source) ~[?:?] {}
	at de.univrsal.justenoughbuttons.client.gui.SaveButton.mouseClicked(SaveButton.java:27) ~[?:1.14.4-1.0] {}
	at de.univrsal.justenoughbuttons.client.handlers.InventorySaveHandler.click(InventorySaveHandler.java:61) ~[?:1.14.4-1.0] {}
	at de.univrsal.justenoughbuttons.client.handlers.EventHandlers.onMousedown(EventHandlers.java:101) ~[?:1.14.4-1.0] {}
	at net.minecraftforge.eventbus.ASMEventHandler_219_EventHandlers_onMousedown_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onGuiMouseClickedPre(ForgeHooksClient.java:913) ~[?:?] {}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3864/1348905109.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:79) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3084/332391051.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at net.minecraft.client.MainWindow.func_216528_l(MainWindow.java:503) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.client.MainWindow.func_198086_a(MainWindow.java:342) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_213227_b(Minecraft.java:944) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:908) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.0.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$350/210474732.call(Unknown Source) [forge-1.14.4-28.1.0.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.univrsal.justenoughbuttons.client.handlers.InventorySaveHandler.lambda$init$0(InventorySaveHandler.java:40)
	at de.univrsal.justenoughbuttons.client.handlers.InventorySaveHandler$$Lambda$3576/1135127963.onPress(Unknown Source)
	at de.univrsal.justenoughbuttons.client.gui.SaveButton.mouseClicked(SaveButton.java:27)
	at de.univrsal.justenoughbuttons.client.handlers.InventorySaveHandler.click(InventorySaveHandler.java:61)
	at de.univrsal.justenoughbuttons.client.handlers.EventHandlers.onMousedown(EventHandlers.java:101)
	at net.minecraftforge.eventbus.ASMEventHandler_219_EventHandlers_onMousedown_Pre.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onGuiMouseClickedPre(ForgeHooksClient.java:913)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper$$Lambda$3864/1348905109.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraftforge.fml.client.gui.GuiModList
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:79)
	at net.minecraft.client.MouseHelper$$Lambda$3084/332391051.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.minecraft.client.MainWindow.func_216528_l(MainWindow.java:503)
	at net.minecraft.client.MainWindow.func_198086_a(MainWindow.java:342)
	at net.minecraft.client.Minecraft.func_213227_b(Minecraft.java:944)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:908)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$350/210474732.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2608370728 bytes (2487 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		adventurepack-1.2.jar Adventure Tools {adventurepack@1.14.4-1.2 DONE}
		AmbientSounds_v3.0.13_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		BetterAdvancements-1.14.4-0.1.0.87.jar Better Advancements {betteradvancements@0.1.0.87 DONE}
		betteranimalsplus-1.14.4-7.1.2.jar Better Animals Plus {betteranimalsplus@7.1.2 DONE}
		BiomesOPlenty-1.14.4-9.0.0.254-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.254 DONE}
		camera-1.4.8.jar Camera Mod {camera@1.4.8 DONE}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 DONE}
		curios-FORGE-1.14.4-1.0.0.3.jar Curios API {curios@FORGE-1.14.4-1.0.0.3 DONE}
		Dirt2Path-1.0.0.jar Dirt2Path {d2p@1.0.0 DONE}
		DoggyTalents-1.14.4-1.15.2.0.jar Doggy Talents {doggytalents@1.15.2.0 DONE}
		extlights-1.6.jar Extended Lights {extlights@1.6 DONE}
		extraboats-1.1.2-1.14.4.jar Extra Boats {extraboats@1.1.2 DONE}
		Fence+Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		furniture-7.0.0-pre10-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre10 DONE}
		Geolosys-1.14.4-4.0.6.jar Geolosys {geolosys@4.0.6 DONE}
		gravestone-1.15.2.jar Gravestone Mod {gravestone@1.15.2 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.18.jar Just Enough Items {jei@6.0.0.18 DONE}
		JRFTL+[1.14.4]-1.1.jar JRFTL {jrftl@1.1 DONE}
		justenoughbuttons-1.14.4-1.0b.jar Just Enough Buttons {justenoughbuttons@1.14.4-1.0 DONE}
		KleeSlabs_1.14.4-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		mcpaint-1.4.5.jar Mc Paint {mcpaint@1.4.5 DONE}
		MouseTweaks-2.11-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.11 DONE}
		overloadedarmorbar-3.0.0.jar Example Mod {overloadedarmorbar@3.0.0 DONE}
		QuickLeafDecay-MC1.14.4-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 DONE}
		searchablechests-1.14-1.5.2.jar Searchable Chests {searchablechests@1.14-1.5.2 DONE}
		SpartanShields-1.14.4-2.0.0-beta-1.jar Spartan Shields {spartanshields@1.14.4-2.0.0-beta-1 DONE}
		StoneCraftingTable-1.14.4-1.0.5.jar Stone Crafting Table {sct@1.0.5 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		switchbow-1.5.8.jar Switch-Bow {switchbow@1.5.8 DONE}
		ToolBelt-1.14.4-1.12.1.jar Tool Belt {toolbelt@1.12.1 DONE}
		viln_1.14-1.0.jar Villager Names {viln@1.0 DONE}
		Waddles-1.14.4-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 DONE}
		Xaeros_Minimap_1.18.4_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.18.4 DONE}
		XaerosWorldMap_1.4.10.1_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.10.1 DONE}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 DONE}
		Aquaculture-1.14.4-2.0.0.jar Aquaculture 2 {aquaculture@1.14.4-2.0.0 DONE}
		forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.1.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.30, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Default 32x32.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor

**Comment by univrsal** [comment]
thanks for letting me know, I'll check it out later today
